## Python Libraries:
#### NUMPY

In [2]:
import numpy as np

In [2]:
#1D array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
#2D array
b = np.array([
    [1.,1.],
    [1.,1.]
])
b

array([[1., 1.],
       [1., 1.]])

In [7]:
c= np.array([1,2,3], dtype = "int16")

In [8]:
print(a)
print(b)
print(c)

[1 2 3]
[[1. 1.]
 [1. 1.]]
[1 2 3]


In [9]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int16


In [15]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
#dimensions of array

1
2
1


In [13]:
print(a.shape)
print(b.shape)
print(c.shape)
#gives shape i.e rows and columns

(3,)
(2, 2)
(3,)


In [14]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
#size of each item in the array

4
8
2


In [23]:
a.size * a.itemsize
#total size of array

12

In [22]:
arr = [range(1,5),range(5,9)]
np.array(arr)
#2D dimentional array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
a = np.array(np.arange(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [9]:
b = np.array([1,5,6,8,1,2,-3,-5,4,7,9,8])
np.count_nonzero(b>0)

10

In [26]:
a.reshape(3,8) #reshaping the 1D into 2D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
a.reshape(2,3,4) #...(z,x,y) 
#reshaping 1D array into 3D array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
c = np.array(np.arange(24)).reshape(2,3,4) *10 +3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [40]:
a = np.array([1,2,3])
c = np.array([4,5,6])
np.append(a,c,axis = 0)

array([1, 2, 3, 4, 5, 6])

In [44]:
a = np.array(np.arange(24)).reshape(2,3,4)
c = np.array(np.arange(24)).reshape(2,3,4) *10 +3
np.append(a,c,axis = 1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [45]:
a = np.array(np.arange(24)).reshape(2,3,4)
c = np.array(np.arange(24)).reshape(2,3,4) *10 +3
np.append(a,c,axis = 2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [49]:
#slicing
a[1,5]

13

In [48]:
a[1][5]

13

In [50]:
a[1][-2]

13

In [56]:
a[0:1,0:5]

array([[1, 2, 3, 4, 5]])

In [57]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
a[:,2]

array([ 3, 10])

### Pandas

Series: 1D array, sequence of elements, associated array of labels(index), 

In [59]:
import numpy as np
import pandas as pd

In [60]:
o1 = pd.Series([4,7,-5,3])
o1

0    4
1    7
2   -5
3    3
dtype: int64

In [61]:
o1.values

array([ 4,  7, -5,  3], dtype=int64)

In [62]:
o2 = pd.Series([4,7,-5,3], index=['a','b','c','d'])
o2

a    4
b    7
c   -5
d    3
dtype: int64

In [63]:
o2['d']

3

In [64]:
o2[0]

4

In [67]:
o3 = pd.Series([1,"Gaurav",3.5,"Aviral"]) #heterogeneous data
o3

0         1
1    Gaurav
2       3.5
3    Aviral
dtype: object

HW:create a list of 10 students with name, age, city and percentage.
-display only names from the series
- display name and percentage
-display percentage >95, <80, =75


#### Dataframe: 

In [68]:
data={"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],      
      "score":[90,80,85,75,95,60,65],      
      "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],      
      "sex":["M","M","M","M","F","F","F"]}

In [73]:
df = pd.DataFrame(data) #converting dictionary into dataframe
df

name  score      sport sex
0     Bill     90  Wrestling   M
1      Tom     80   Football   M
2      Tim     85     Skiing   M
3     John     75   Swimming   M
4     Alex     95     Tennis   F
5  Vanessa     60     Karete   F
6     Kate     65    Surfing   F

In [74]:
df.head(2)

name  score      sport sex
0  Bill     90  Wrestling   M
1   Tom     80   Football   M

In [75]:
df.tail(2)

name  score    sport sex
5  Vanessa     60   Karete   F
6     Kate     65  Surfing   F

In [77]:
df = pd.DataFrame(data, columns=["name", "score", "sport","sex","age"])

In [78]:
df

name  score      sport sex  age
0     Bill     90  Wrestling   M  NaN
1      Tom     80   Football   M  NaN
2      Tim     85     Skiing   M  NaN
3     John     75   Swimming   M  NaN
4     Alex     95     Tennis   F  NaN
5  Vanessa     60     Karete   F  NaN
6     Kate     65    Surfing   F  NaN

In [79]:
df["sport"]

0    Wrestling
1     Football
2       Skiing
3     Swimming
4       Tennis
5       Karete
6      Surfing
Name: sport, dtype: object

In [81]:
df1 = ["sport","name"]
df[df1]

sport     name
0  Wrestling     Bill
1   Football      Tom
2     Skiing      Tim
3   Swimming     John
4     Tennis     Alex
5     Karete  Vanessa
6    Surfing     Kate

In [82]:
df["age"] = 20

In [83]:
df

name  score      sport sex  age
0     Bill     90  Wrestling   M   20
1      Tom     80   Football   M   20
2      Tim     85     Skiing   M   20
3     John     75   Swimming   M   20
4     Alex     95     Tennis   F   20
5  Vanessa     60     Karete   F   20
6     Kate     65    Surfing   F   20

HW : read and write data in different formats:
- 7 example datasets
- try to make use of separator
(pd.read_table('exe1.csv',sep=','))
-try to change column names
-try to change index in word format
-try to read .jason file

HW: use given sports dataset and explore the dataset

In [10]:
import pandas as pd
   
# create a new data frame
df = pd.DataFrame({'Name': ['John_Larter', 'Robert_Junior', 'Jonny_Depp'],
                    'Age':[32, 34, 36]})
   
print("Given Dataframe is :\n",df)
  
print("\nSplitting Name column into two different columns :") 
print(pd.DataFrame(df.Name.str.split('_',1).tolist(),
                         columns = ['first','Last']))

Given Dataframe is :
             Name  Age
0    John_Larter   32
1  Robert_Junior   34
2     Jonny_Depp   36

Splitting Name column into two different columns :
    first    Last
0    John  Larter
1  Robert  Junior
2   Jonny    Depp


In [15]:
Name= ['Amol', 'Abhi','Shubham', 'Rahul','Sadiya','Pratik', 'Ruchira','Aishwarya','Keshav','Yash']
Age= [20,21,22,23,24,25,26,27,28,29]
City=['Nagpur','Nashik','Pune','Ahmednagar','Mumbai','Ratnagiri', 'Aurangabad','Kolhapur','Amravati','Yavatmal']
Percentage=[75.0,60.0,65.0,75.0,99.23,77.20,97.0,96.40,65.20,44.30]
a=list(zip(Name,Percentage))
b=int(input("Enter a choice to view panda series:"))
if b==1:
  c=pd.Series(Name)
  print(c)
elif b==2:
  c=pd.Series(a)
  print(c)
elif b==3:
  c=pd.Series(Percentage)
  x=int(input("Enter a choice to check percentage :"))
  if x==1:
    c=c.where(c>95)
    print(c)
  elif x==2:
    c=c.where(c==75)
    print(c)
  elif x==3:
    c=c.where(c<80)
    print(c)
else:
  print("Choose proper option \n Try Again")


Enter a choice to view panda series:3
Enter a choice to check percentage :1


TypeError: Cannot perform 'ror_' with a dtyped [float64] array and scalar of type [bool]